name: Build & Push to ACR

on:
  push:
    branches:
      - main   # Change if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Give gradlew permissions
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Build JAR (skip tests)
      - name: Build JAR
        run: ./gradlew :services:platform-initializer:clean :services:platform-initializer:bootJar -x test

      # 5. Login to ACR
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}   # Example: myregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 6. Build Docker image
      - name: Build Docker Image
        run: |
          docker build --no-cache \
            --build-arg SERVICE=platform-initializer \
            --build-arg GRADLE_ARGS="-Pci=true -PskipDocker=true -PskipAzChecks=true" \
            -t ${{ secrets.ACR_SERVER }}/${{ secrets.NS }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .

      # 7. Push Docker image to ACR
      - name: Push Docker Image
        run: docker push ${{ secrets.ACR_SERVER }}/${{ secrets.NS }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
