name: CI for Microservices & Common Modules

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: 
          - platform-initializer
          - tenant-service
          - notification-service
          - commons
          - utilities
          # add more services here if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Gradle Wrapper permission
        run: chmod +x ./gradlew

      # ------------------------
      # Dockerized services
      # ------------------------
      - name: Build Docker image for microservice
        if: contains(matrix.module, 'service') || matrix.module == 'platform-initializer' || matrix.module == 'tenant-service' || matrix.module == 'notification-service'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Image
        if: contains(matrix.module, 'service') || matrix.module == 'platform-initializer' || matrix.module == 'tenant-service' || matrix.module == 'notification-service'
        run: |
          docker build --build-arg SERVICE=${{ matrix.module }} -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.module }}:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.module }}:${{ github.sha }}
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.module }}:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.module }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.module }}:latest

      # ------------------------
      # Non-docker modules
      # ------------------------
      - name: Build non-docker module
        if: matrix.module == 'commons' || matrix.module == 'utilities'
        run: ./gradlew ":${{ matrix.module }}:build" -x test --no-daemon

      - name: Upload artifacts for non-docker modules
        if: matrix.module == 'commons' || matrix.module == 'utilities'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.module }}-artifact
          path: ${{ matrix.module }}/build/libs/*.jar
